.TH ZIPXF 1 zipxf\-0.1
.SH NAME
zipxf \- zip/unzip an archive
.SH SYNOPSIS
.B zipxf
.RB [ \-z
.IR archive.zip ]
.RB [ \-u
.IR archive.zip ]
.P
.BR zipxf " ..."
.SH DESCRIPTION
.B zipxf
Zips all files in current working directory into an archive or Unzips an archive into current working directory.
.SH OPTIONS
.TP
.B \-z
zip all files within current working dir into an archive
.TP
.B \-u
unzip an archive into current working directory
.SH AUTHOR
.B Jb Williams
